freeze("$(PORT_DIR)/modules")
include("$(MPY_DIR)/extmod/asyncio")
require("onewire")
require("ds18x20")
require("dht")
require("neopixel")
# module("/home/pi/partage/st7789_4bit/st7789_4bit.py")
# module("obj_LED_stip.mpy", base_path="/home/pi/partage/stub")
# freeze(path="/home/pi/partage/simpleButton")
package(package_path="",base_path="/home/pi/echange/sources_for_FW")